"""
Molecule serialization to various formats (.molforge, .mol, .pdb).
"""
import json
from typing import Dict, List, Tuple
from .models import Atom, Bond


class MoleculeSerializer:
    """
    Handles exporting and importing molecule structures in:
    - .molforge (JSON)
    - .mol (V2000)
    - .pdb (simple)
    """

    @staticmethod
    def to_molforge(atoms: Dict[int, Atom], bonds: List[Bond], positions: Dict[int, Tuple[float, float, float]]) -> str:
        """Export to native .molforge JSON format."""
        payload = {
            "atoms": {
                str(k): {
                    "id": v.id,
                    "element": v.element,
                    "charge": getattr(v, "charge", 0)
                }
                for k, v in atoms.items()
            },
            "positions": {
                str(k): list(pos)
                for k, pos in positions.items()
            },
            "bonds": [
                {
                    "atom_a": b.atom_a,
                    "atom_b": b.atom_b,
                    "order": b.order
                }
                for b in bonds
            ]
        }
        return json.dumps(payload, indent=2)

    @staticmethod
    def to_mol(atoms: Dict[int, Atom], bonds: List[Bond], positions: Dict[int, Tuple[float, float, float]]) -> str:
        """Export to .mol V2000 format."""
        atom_lines = []
        bond_lines = []

        atom_order = sorted(atoms.keys())

        # Atom block
        for idx in atom_order:
            x, y, z = positions[idx]
            el = atoms[idx].element
            atom_lines.append(f"{x:10.4f}{y:10.4f}{z:10.4f} {el:>3} 0  0  0  0  0  0  0  0  0  0")

        # Bond block
        atom_to_idx = {atom_id: i+1 for i, atom_id in enumerate(atom_order)}

        for b in bonds:
            a = atom_to_idx[b.atom_a]
            c = atom_to_idx[b.atom_b]
            bond_lines.append(f"{a:3d}{c:3d}{b.order:3d}  0  0  0  0")

        header = [
            "MolForge Export",
            "Generated by MolForge",
            ""
        ]

        counts_line = f"{len(atoms):3d}{len(bonds):3d}  0  0  0  0            999 V2000"

        return "\n".join(header + [counts_line] + atom_lines + bond_lines + ["M  END"])

    @staticmethod
    def to_pdb(atoms: Dict[int, Atom], positions: Dict[int, Tuple[float, float, float]]) -> str:
        """Export to simple .pdb format (ATOM lines only)."""
        lines = []
        for idx, atom in atoms.items():
            x, y, z = positions[idx]
            lines.append(
                f"ATOM  {idx:5d} {atom.element:<2}   MOL     1    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           {atom.element:>2}"
            )
        lines.append("END")
        return "\n".join(lines)
